apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x6o7p10hx-go 
  janus-idp.io/tekton: x6o7p10hx-go
  backstage.io/kubernetes-id: x6o7p10hx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x6o7p10hx-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml