apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: x6o7p10hx-go-gitops
  description: This is GitOps manifest for x6o7p10hx-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=x6o7p10hx-go
    backstage.io/kubernetes-id: x6o7p10hx-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: x6o7p10hx-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:x6o7p10hx-go
